const fs = require('fs');
let content = fs.readFileSync('/app/applet/components/SpotifyNowPlayingView.tsx', 'utf-8');

content = content.replace(
    '    if (song.collaboration) {\n        const collabProfile = allPlayerArtists.find(a => a.name === song.collaboration?.artistName);\n        if (collabProfile) {\n            artistsToDisplay.push({ name: collabProfile.name, image: collabProfile.images?.[0] || `https://ui-avatars.com/api/?name=${encodeURIComponent(collabProfile.name)}&background=random` });\n        } else {\n            artistsToDisplay.push({ name: song.collaboration.artistName, image: NPC_ARTIST_IMAGES[song.collaboration.artistName] || `https://ui-avatars.com/api/?name=${encodeURIComponent(song.collaboration.artistName)}&background=random` });\n        }\n    }',
    '    if (song.features && song.features.length > 0) {\n        song.features.forEach(f => {\n            const collabProfile = allPlayerArtists.find(a => a.name === f);\n            if (collabProfile) {\n                artistsToDisplay.push({ name: collabProfile.name, image: collabProfile.images?.[0] || `https://ui-avatars.com/api/?name=${encodeURIComponent(collabProfile.name)}&background=random` });\n            } else {\n                artistsToDisplay.push({ name: f, image: NPC_ARTIST_IMAGES[f] || `https://ui-avatars.com/api/?name=${encodeURIComponent(f)}&background=random` });\n            }\n        });\n    }\n    if (song.collaboration) {\n        const collabProfile = allPlayerArtists.find(a => a.name === song.collaboration?.artistName);\n        if (collabProfile) {\n            artistsToDisplay.push({ name: collabProfile.name, image: collabProfile.images?.[0] || `https://ui-avatars.com/api/?name=${encodeURIComponent(collabProfile.name)}&background=random` });\n        } else {\n            artistsToDisplay.push({ name: song.collaboration.artistName, image: NPC_ARTIST_IMAGES[song.collaboration.artistName] || `https://ui-avatars.com/api/?name=${encodeURIComponent(song.collaboration.artistName)}&background=random` });\n        }\n    }'
);

fs.writeFileSync('/app/applet/components/SpotifyNowPlayingView.tsx', content);
console.log("Fixed spotify now playing");
