const fs = require('fs');

const file_path = '/app/applet/constants.ts';
let content = fs.readFileSync(file_path, 'utf8');

// I'll append a lot of venues to each tier!
const smallHalls = `
{ name: "First Direct Arena", city: "Leeds", capacity: 13000, region: "Europe" },
{ name: "Motorpoint Arena", city: "Nottingham", capacity: 10000, region: "Europe" },
{ name: "AO Arena", city: "Manchester", capacity: 21000, region: "Europe" },
{ name: "3Arena", city: "Dublin", capacity: 13000, region: "Europe" },
{ name: "Scotiabank Arena", city: "Toronto", capacity: 19800, region: "North America" },
{ name: "Centre Bell", city: "Montreal", capacity: 21273, region: "North America" },
{ name: "Qudos Bank Arena", city: "Sydney", capacity: 21000, region: "Oceania" },
{ name: "Rod Laver Arena", city: "Melbourne", capacity: 14820, region: "Oceania" },
{ name: "Zepp DiverCity", city: "Tokyo", capacity: 2473, region: "Asia" },
{ name: "Yes24 Live Hall", city: "Seoul", capacity: 2000, region: "Asia" },
`;

// Wait, I can just use a regex to insert into each array inside VENUES object
const arenasList = `
{ name: "Madison Square Garden", city: "New York", capacity: 19500, region: "North America" },
{ name: "Staples Center", city: "Los Angeles", capacity: 20000, region: "North America" },
{ name: "United Center", city: "Chicago", capacity: 23500, region: "North America" },
{ name: "Wells Fargo Center", city: "Philadelphia", capacity: 21000, region: "North America" },
{ name: "TD Garden", city: "Boston", capacity: 19580, region: "North America" },
{ name: "State Farm Arena", city: "Atlanta", capacity: 21000, region: "North America" },
{ name: "American Airlines Center", city: "Dallas", capacity: 20000, region: "North America" },
{ name: "Chase Center", city: "San Francisco", capacity: 18064, region: "North America" },
{ name: "O2 Arena", city: "London", capacity: 20000, region: "Europe" },
{ name: "Accor Arena", city: "Paris", capacity: 20300, region: "Europe" },
{ name: "Lanxess Arena", city: "Cologne", capacity: 20000, region: "Europe" },
{ name: "Mercedes-Benz Arena", city: "Berlin", capacity: 17000, region: "Europe" },
{ name: "Ziggo Dome", city: "Amsterdam", capacity: 17000, region: "Europe" },
{ name: "O2 Arena Prague", city: "Prague", capacity: 18000, region: "Europe" },
{ name: "Wiener Stadthalle", city: "Vienna", capacity: 16152, region: "Europe" },
{ name: "Palau Sant Jordi", city: "Barcelona", capacity: 17000, region: "Europe" },
{ name: "Wizink Center", city: "Madrid", capacity: 17453, region: "Europe" },
{ name: "Jeunesse Arena", city: "Rio de Janeiro", capacity: 18000, region: "South America" },
{ name: "Allianz Parque", city: "Sao Paulo", capacity: 43713, region: "South America" }, // Wait, this is a stadium, but maybe arena size configuration
{ name: "Movistar Arena", city: "Santiago", capacity: 15000, region: "South America" },
{ name: "Movistar Arena", city: "Buenos Aires", capacity: 15000, region: "South America" },
{ name: "Movistar Arena", city: "Bogota", capacity: 14000, region: "South America" },
{ name: "Saitama Super Arena", city: "Saitama", capacity: 36500, region: "Asia" },
{ name: "Yokohama Arena", city: "Yokohama", capacity: 17000, region: "Asia" },
{ name: "KSPO Dome", city: "Seoul", capacity: 15000, region: "Asia" },
{ name: "Impact Arena", city: "Bangkok", capacity: 11000, region: "Asia" },
{ name: "Philippine Arena", city: "Bulacan", capacity: 51898, region: "Asia" }, // Huge arena
{ name: "Mall of Asia Arena", city: "Manila", capacity: 15000, region: "Asia" },
{ name: "Singapore Indoor Stadium", city: "Singapore", capacity: 12000, region: "Asia" },
{ name: "Coca-Cola Arena", city: "Dubai", capacity: 17000, region: "Middle East" },
`;

const stadiumList = `
{ name: "Estadio Nacional", city: "Lima", capacity: 50000, region: "South America" },
{ name: "Estadio Monumental U", city: "Lima", capacity: 80000, region: "South America" },
{ name: "Estadio Monumental", city: "Buenos Aires", capacity: 84567, region: "South America" },
{ name: "Estadio Unico de La Plata", city: "La Plata", capacity: 53000, region: "South America" },
{ name: "Estadio Nacional", city: "Santiago", capacity: 48665, region: "South America" },
{ name: "Estadio El Campin", city: "Bogota", capacity: 39000, region: "South America" },
{ name: "Estadio Atanasio Girardot", city: "Medellin", capacity: 40043, region: "South America" },
{ name: "Estadio Azteca", city: "Mexico City", capacity: 87523, region: "North America" },
{ name: "Foro Sol", city: "Mexico City", capacity: 65000, region: "North America" },
{ name: "Estadio BBVA", city: "Monterrey", capacity: 51000, region: "North America" },
{ name: "Estadio Akron", city: "Guadalajara", capacity: 49850, region: "North America" },
{ name: "Rogers Centre", city: "Toronto", capacity: 49282, region: "North America" },
{ name: "BC Place", city: "Vancouver", capacity: 54500, region: "North America" },
{ name: "Commonwealth Stadium", city: "Edmonton", capacity: 56302, region: "North America" },
{ name: "Olympic Stadium", city: "Montreal", capacity: 56040, region: "North America" },
{ name: "Lumen Field", city: "Seattle", capacity: 68740, region: "North America" },
{ name: "Levi's Stadium", city: "Santa Clara", capacity: 68500, region: "North America" },
{ name: "Rose Bowl", city: "Pasadena", capacity: 92542, region: "North America" },
{ name: "SoFi Stadium", city: "Inglewood", capacity: 70240, region: "North America" },
{ name: "Allegiant Stadium", city: "Las Vegas", capacity: 65000, region: "North America" },
{ name: "State Farm Stadium", city: "Glendale", capacity: 63400, region: "North America" },
{ name: "AT&T Stadium", city: "Arlington", capacity: 80000, region: "North America" },
{ name: "NRG Stadium", city: "Houston", capacity: 72220, region: "North America" },
{ name: "Caesars Superdome", city: "New Orleans", capacity: 73208, region: "North America" },
{ name: "Mercedes-Benz Stadium", city: "Atlanta", capacity: 71000, region: "North America" },
{ name: "Hard Rock Stadium", city: "Miami Gardens", capacity: 64767, region: "North America" },
{ name: "Raymond James Stadium", city: "Tampa", capacity: 65890, region: "North America" },
{ name: "Bank of America Stadium", city: "Charlotte", capacity: 74867, region: "North America" },
{ name: "Nissan Stadium", city: "Nashville", capacity: 69143, region: "North America" },
{ name: "Soldier Field", city: "Chicago", capacity: 61500, region: "North America" },
{ name: "Ford Field", city: "Detroit", capacity: 65000, region: "North America" },
{ name: "Lucas Oil Stadium", city: "Indianapolis", capacity: 67000, region: "North America" },
{ name: "Paycor Stadium", city: "Cincinnati", capacity: 65515, region: "North America" },
{ name: "Cleveland Browns Stadium", city: "Cleveland", capacity: 67431, region: "North America" },
{ name: "Acrisure Stadium", city: "Pittsburgh", capacity: 68400, region: "North America" },
{ name: "Lincoln Financial Field", city: "Philadelphia", capacity: 69796, region: "North America" },
{ name: "MetLife Stadium", city: "East Rutherford", capacity: 82500, region: "North America" },
{ name: "Gillette Stadium", city: "Foxborough", capacity: 65878, region: "North America" },
{ name: "Wembley Stadium", city: "London", capacity: 90000, region: "Europe" },
{ name: "Tottenham Hotspur Stadium", city: "London", capacity: 62850, region: "Europe" },
{ name: "London Stadium", city: "London", capacity: 60000, region: "Europe" },
{ name: "Principality Stadium", city: "Cardiff", capacity: 74500, region: "Europe" },
{ name: "Murrayfield Stadium", city: "Edinburgh", capacity: 67144, region: "Europe" },
{ name: "Aviva Stadium", city: "Dublin", capacity: 51700, region: "Europe" },
{ name: "Croke Park", city: "Dublin", capacity: 82300, region: "Europe" },
{ name: "Stade de France", city: "Paris", capacity: 80698, region: "Europe" },
{ name: "Groupama Stadium", city: "Lyon", capacity: 59186, region: "Europe" },
{ name: "Orange Vélodrome", city: "Marseille", capacity: 67394, region: "Europe" },
{ name: "Olympiastadion", city: "Berlin", capacity: 74475, region: "Europe" },
{ name: "Olympiastadion", city: "Munich", capacity: 69250, region: "Europe" },
{ name: "Allianz Arena", city: "Munich", capacity: 75024, region: "Europe" },
{ name: "Deutsche Bank Park", city: "Frankfurt", capacity: 51500, region: "Europe" },
{ name: "Merkur Spiel-Arena", city: "Dusseldorf", capacity: 54600, region: "Europe" },
{ name: "RheinEnergieStadion", city: "Cologne", capacity: 50000, region: "Europe" },
{ name: "Volksparkstadion", city: "Hamburg", capacity: 57000, region: "Europe" },
{ name: "Johan Cruyff Arena", city: "Amsterdam", capacity: 55500, region: "Europe" },
{ name: "Koning Boudewijnstadion", city: "Brussels", capacity: 50093, region: "Europe" },
{ name: "San Siro", city: "Milan", capacity: 75923, region: "Europe" },
{ name: "Stadio Olimpico", city: "Rome", capacity: 70634, region: "Europe" },
{ name: "Santiago Bernabéu", city: "Madrid", capacity: 81044, region: "Europe" },
{ name: "Estadio Metropolitano", city: "Madrid", capacity: 70460, region: "Europe" },
{ name: "Camp Nou", city: "Barcelona", capacity: 99354, region: "Europe" },
{ name: "Estadi Olímpic Lluís Companys", city: "Barcelona", capacity: 55926, region: "Europe" },
{ name: "PGE Narodowy", city: "Warsaw", capacity: 58145, region: "Europe" },
{ name: "Friends Arena", city: "Stockholm", capacity: 50622, region: "Europe" },
{ name: "Ullevi", city: "Gothenburg", capacity: 43000, region: "Europe" },
{ name: "Telenor Arena", city: "Oslo", capacity: 25000, region: "Europe" }, // technically an arena but acts as stadium
{ name: "Parken", city: "Copenhagen", capacity: 38065, region: "Europe" },
{ name: "Luzhniki Stadium", city: "Moscow", capacity: 81000, region: "Europe" },
{ name: "Tokyo Dome", city: "Tokyo", capacity: 55000, region: "Asia" },
{ name: "Ajinomoto Stadium", city: "Tokyo", capacity: 49970, region: "Asia" },
{ name: "Nissan Stadium", city: "Yokohama", capacity: 72327, region: "Asia" },
{ name: "Yanai Stadium", city: "Osaka", capacity: 47000, region: "Asia" },
{ name: "Kyocera Dome", city: "Osaka", capacity: 36477, region: "Asia" },
{ name: "Mizuho Stadium", city: "Nagoya", capacity: 27000, region: "Asia" },
{ name: "Fukuoka PayPay Dome", city: "Fukuoka", capacity: 38561, region: "Asia" },
{ name: "Sapporo Dome", city: "Sapporo", capacity: 41484, region: "Asia" },
{ name: "Seoul Olympic Stadium", city: "Seoul", capacity: 69950, region: "Asia" },
{ name: "Seoul World Cup Stadium", city: "Seoul", capacity: 66704, region: "Asia" },
{ name: "Gocheok Sky Dome", city: "Seoul", capacity: 16744, region: "Asia" }, // smaller but often stadium acts play here
{ name: "National Stadium", city: "Beijing", capacity: 80000, region: "Asia" },
{ name: "Shanghai Stadium", city: "Shanghai", capacity: 56842, region: "Asia" },
{ name: "Hong Kong Stadium", city: "Hong Kong", capacity: 40000, region: "Asia" },
{ name: "Taipei Dome", city: "Taipei", capacity: 40000, region: "Asia" },
{ name: "National Stadium", city: "Kaohsiung", capacity: 55000, region: "Asia" },
{ name: "Rajamangala Stadium", city: "Bangkok", capacity: 51552, region: "Asia" },
{ name: "National Stadium", city: "Bukit Jalil", capacity: 87411, region: "Asia" },
{ name: "Gelora Bung Karno Stadium", city: "Jakarta", capacity: 77193, region: "Asia" },
{ name: "Philippine Sports Stadium", city: "Bocaue", capacity: 25000, region: "Asia" },
{ name: "Singapore National Stadium", city: "Singapore", capacity: 55000, region: "Asia" },
{ name: "DY Patil Stadium", city: "Mumbai", capacity: 55000, region: "Asia" },
{ name: "Jawaharlal Nehru Stadium", city: "Delhi", capacity: 60000, region: "Asia" },
{ name: "King Fahd International Stadium", city: "Riyadh", capacity: 68000, region: "Middle East" },
{ name: "Lusail Stadium", city: "Lusail", capacity: 88966, region: "Middle East" },
{ name: "Zayed Sports City Stadium", city: "Abu Dhabi", capacity: 45000, region: "Middle East" },
{ name: "FNB Stadium", city: "Johannesburg", capacity: 94736, region: "Africa" },
{ name: "Cape Town Stadium", city: "Cape Town", capacity: 55000, region: "Africa" },
{ name: "Moses Mabhida Stadium", city: "Durban", capacity: 54000, region: "Africa" },
{ name: "Cairo International Stadium", city: "Cairo", capacity: 75000, region: "Africa" },
{ name: "MCG", city: "Melbourne", capacity: 100024, region: "Oceania" },
{ name: "Marvel Stadium", city: "Melbourne", capacity: 53359, region: "Oceania" },
{ name: "Accor Stadium", city: "Sydney", capacity: 83500, region: "Oceania" },
{ name: "Allianz Stadium", city: "Sydney", capacity: 42500, region: "Oceania" },
{ name: "Suncorp Stadium", city: "Brisbane", capacity: 52500, region: "Oceania" },
{ name: "Optus Stadium", city: "Perth", capacity: 60000, region: "Oceania" },
{ name: "Adelaide Oval", city: "Adelaide", capacity: 53583, region: "Oceania" },
{ name: "Eden Park", city: "Auckland", capacity: 50000, region: "Oceania" }
`;

content = content.replace(
    "'Arenas': [",
    "'Arenas': [\n" + arenasList + ","
);

content = content.replace(
    "'Stadiums': [",
    "'Stadiums': [\n" + stadiumList + ","
);

fs.writeFileSync(file_path, content);
console.log("Patched constants venues heavily");
